name: TypeScript CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # pin@v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # pin@v4.2.0
        with:
          version: 10.17.0
      - name: Install Nodejs
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # pin@v6.0.0
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'examples/frontend/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
